### PR TITLE
Tomoviewer

### PR DESCRIPTION
**Pull request by MariaMatveeva**
Rotation axis options and view were added. The gui is based on the old version because the new one (since commit https://github.com/ufo-kit/ufo-scripts/commit/4580d66525cbecc672734a0c8210f110015bef4f ) doesn't work.

### CODE REVIEW

**Comment by tfarago** [comment]
I wanted to show some slices in the 3D mode and got the following:

```python
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/unfoog/gui.py", line 604, in show_slices
  File "build/bdist.linux-x86_64/egg/unfoog/gui.py", line 661, in make_volume_layout
  File "/home/farago/virtenvs/concert/local/lib/python2.7/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 54, in addItem
    self.checkOpenGLVersion('Error while adding item %s to GLViewWidget.' % str(item))
  File "/home/farago/virtenvs/concert/local/lib/python2.7/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 52, in addItem
    item.initializeGL()
  File "/home/farago/virtenvs/concert/local/lib/python2.7/site-packages/pyqtgraph/opengl/items/GLVolumeItem.py", line 45, in initializeGL
    shape = self.data.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

Do I need some special version of pyqtgraph?

**Comment by matze** [comment]
You probably need the very latest version of PyQtGraph. I just changed the code that it works with more widespread versions.

**Comment by matze** [comment]
I just rebased against master. In order to maintain this more thoroughly, I'd suggest to merge this ASAP.

**Comment by matze** [comment]
No objections? Good :smile:

**Comment by tfarago** [comment]
Yep, good idea.

**Pull request merged**
