### PR TITLE
Flat correction

### PR DESCRIPTION
**Pull request by tfarago**
I needed to do simple flat correction and got stuck, hence this. @MariaMatveeva please check the GUI parts, I had to change some things in order to make it work with the new features. I will also point out some things in the code.

### CODE REVIEW

**Comment by matze** [comment]
So, is this good for review?

**Comment by MariaMatveeva** [comment]
@tfarago the axis doesn't seem to look right anymore. I use the bug sinograms and projections with axis 413.

**Comment by tfarago** [comment]
It works for me. If you give me path to your data I can take a look.

**Comment by MariaMatveeva** [comment]
@tfarago oh sorry, it works on your branch.

**Comment by tfarago** [comment]
Then yes, ready to be reviewed.

**Comment by matze** [comment]
Code looks good, program works, :+1:

**Comment by tfarago** [comment]
@MariaMatveeva do you want to update the GUI within this PR or should I merge and you do it separately?

**Comment by MariaMatveeva** [comment]
@tfarago You can merge, I'll do it separately. It's only the "fix nan and inf" checkbox or there are more things? Where do you want it to be?

**Comment by tfarago** [comment]
OK, no I think that's it. The checkbox should be somewhere by the flat correction options.

**Pull request merged**
